### ISSUE TITLE
Phantom 4 udp packet sniffing

### ISSUE THREAD

**Issue by chooostar** [Toemsel/dji-wifi-tools#1]
Hello, I want to use this program to Phantom 4 standard,
but I don't know how to use it.

I had complete install this program, but I can't connect to the Phantom 4 wifi...
How can I connect to DJI Phantom 4 wifi? Or, this program do not need wifi connect?????

Thank you!!

**Comment by Toemsel** [comment]
Sup. I haven't tested it with PH4 yet, so keep that in mind. The app itself doesn't connect automatically to the drone. You do require to connect your smartphone (running the dji go app) to your PC/Notebook. Then, connect the notebook to the drone. Now start the application. If you tunnel the traffic correctly between both NICs the app should then detect the drone and operator just fine.

**Comment by chooostar** [comment]
Thank you for answer!!!
Um, in Readme.md , the program support mavic pro 1, phantom3, phantom4
PH3 use wifi , I know, (I don't know about Mavic pro 1)
 **But, as far as I know, PH4 doesn't use wifi .** So controller and mobile have wired connection.
So,do you mean both PC and drone, mobile and PC need wired connection?

**Comment by Toemsel** [comment]
PH4 Pro has WiFi. If you have the PH4, then you wont be able to use this tool, as it is only build for WiFi.
