### ISSUE TITLE
PH4 pro 2.0 

### ISSUE THREAD

**Issue by chooostar** [Toemsel/dji-wifi-tools#2]
Hello, I have a Phantom 4 pro v2.0, use OcuSync2.0 instead of Lightbridge.

I want to use this dji-wifi-tools to my PH4 pro 2.0, but I don't know how.
I think PH4 pro 2.0 doesn't use wifi. 
(But PH4 pro doesn't use wifi during flying, I think..?)

If you use this tool to the PH4 pro 2.0 , could you explaing me how to use it?

Thank you.

**Comment by Toemsel** [comment]
https://github.com/Toemsel/dji-wifi-tools/issues/1
